// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionWebApi.Controllers;

#nullable disable

namespace TransactionWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231224162951_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionWebApi.Controllers.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TransactionWebApi.Controllers.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TransactionWebApi.Controllers.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Challenger",
                            Price = 216224.92352367866000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 2,
                            Name = "Durango",
                            Price = 36502.4080079099575000m,
                            Stock = 197
                        },
                        new
                        {
                            Id = 3,
                            Name = "Golf",
                            Price = 93202.373134600082000m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 4,
                            Name = "ATS",
                            Price = 16076.3372800970824000m,
                            Stock = 136
                        },
                        new
                        {
                            Id = 5,
                            Name = "Silverado",
                            Price = 382867.307314525611000m,
                            Stock = 181
                        },
                        new
                        {
                            Id = 6,
                            Name = "1",
                            Price = 337729.796551835775000m,
                            Stock = 97
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accord",
                            Price = 419910.789276584406000m,
                            Stock = 193
                        },
                        new
                        {
                            Id = 8,
                            Name = "CX-9",
                            Price = 184594.835864411129000m,
                            Stock = 54
                        },
                        new
                        {
                            Id = 9,
                            Name = "Countach",
                            Price = 161822.031192351469000m,
                            Stock = 138
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cruze",
                            Price = 319923.513459619812000m,
                            Stock = 70
                        });
                });

            modelBuilder.Entity("TransactionWebApi.Controllers.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
