// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionWebApi.Controllers;

#nullable disable

namespace TransactionWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231224165451_mg2")]
    partial class mg2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionWebApi.Controllers.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TransactionWebApi.Controllers.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TransactionWebApi.Controllers.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Prius",
                            Price = 217577.700944395137000m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 2,
                            Name = "Camry",
                            Price = 391295.064132465291000m,
                            Stock = 83
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ranchero",
                            Price = 20196.0507852972058000m,
                            Stock = 68
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wrangler",
                            Price = 492078.495790893581000m,
                            Stock = 153
                        },
                        new
                        {
                            Id = 5,
                            Name = "1",
                            Price = 438002.38308338079000m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 6,
                            Name = "Civic",
                            Price = 89721.358466867144000m,
                            Stock = 131
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spyder",
                            Price = 288883.147270575727000m,
                            Stock = 190
                        },
                        new
                        {
                            Id = 8,
                            Name = "Spyder",
                            Price = 73129.938574920958000m,
                            Stock = 168
                        },
                        new
                        {
                            Id = 9,
                            Name = "1",
                            Price = 80782.477600920856000m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "1",
                            Price = 481210.060187187636000m,
                            Stock = 74
                        });
                });

            modelBuilder.Entity("TransactionWebApi.Controllers.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("TransactionWebApi.Controllers.ShoppingCart", b =>
                {
                    b.HasOne("TransactionWebApi.Controllers.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
